name: Deploy Production

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup

      - name: Lint
        run: yarn lint
  
  deploy:
    needs: lint
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup

      - name: Deploy to Cloudflare
        run: npx wrangler publish -e production
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
